version: '3'

services:
  marsweather:
    container_name: marsweather
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: marsweather
      SLEEP_TIME: 60

networks:
  default:
    external:
      name: kafka-network