version: '3'

services:
  weatherconsumer:
    container_name: weatherconsumer
    image: weatherconsumer  # Updated the image name
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: weather
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u", "python/weather_consumer.py"]

networks:
  default:
    external:
      name: kafka-network
