version: '3'

services:
  weatherconsumer:
    container_name: weatherconsumer
    image: consumer
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: weather
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u","python/weather_consumer.py"]
  fakerconsumer:
    container_name: fakerconsumer
    image: consumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: faker
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u","python/faker_consumer.py"]
  marsweatherconsumer:
    container_name: marsweatherconsumer
    image: consumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: marsweather
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u","python/marsweather_consumer.py"]
  neoconsumer:
    container_name: neoconsumer
    image: consumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: near_earth_objects
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u","python/neo_consumer.py"]

networks:
  default:
    external:
      name: kafka-network
