version: '3'

services:
  near_earth_objects:
    container_name: near_earth_objects
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: near_earth_objects
      SLEEP_TIME: 60

networks:
  default:
    external:
      name: kafka-network