services:
  cassandradb:
    container_name: cassandra
    image: bootstrapcassandra
    build: .
    ports:
      - 8081:8081
      - 9042:9042
    volumes:
      - $PWD/cassandra/data:/var/lib/cassandra
    networks:
      - cassandra-network

networks:
  cassandra-network:
    external: true
